/**
 * SolanaWalletProvider
 *
 * Wraps the application with Solana wallet adapter providers.
 * This component sets up the connection, wallet context, and
 * Mobile Wallet Adapter for use throughout the app.
 *
 * Generated by SeekerMigrate for sample-ios-firebase-app
 * @generated
 */

import React, { useMemo } from 'react';
import {
  ConnectionProvider,
  WalletProvider,
} from '@solana/wallet-adapter-react';
import { clusterApiUrl } from '@solana/web3.js';
import { WalletAuthProvider } from './WalletAuthContext';

// Solana cluster configuration
const SOLANA_CLUSTER = 'devnet';

// RPC endpoint - replace with your own for production
const RPC_ENDPOINT = clusterApiUrl(SOLANA_CLUSTER);

// For better performance in production, consider using a dedicated RPC:
// const RPC_ENDPOINT = 'https://your-rpc-endpoint.com';

/**
 * Props for SolanaWalletProvider
 */
interface SolanaWalletProviderProps {
  children: React.ReactNode;
  autoConnect?: boolean;
}

/**
 * Provides Solana wallet functionality to the app
 *
 * @example
 * // In your App.js/App.tsx:
 * import { SolanaWalletProvider } from './SolanaWalletProvider';
 *
 * function App() {
 *   return (
 *     <SolanaWalletProvider>
 *       <YourAppContent />
 *     </SolanaWalletProvider>
 *   );
 * }
 */
export function SolanaWalletProvider({
  children,
  autoConnect = false,
}: SolanaWalletProviderProps) {
  // Wallets configuration
  // Mobile Wallet Adapter is handled automatically by the protocol
  const wallets = useMemo(() => [], []);

  return (
    <ConnectionProvider endpoint={RPC_ENDPOINT}>
      <WalletProvider wallets={wallets} autoConnect={autoConnect}>
        <WalletAuthProvider>
          {children}
        </WalletAuthProvider>
      </WalletProvider>
    </ConnectionProvider>
  );
}

/**
 * HOC to wrap a component with wallet provider
 */
export function withWalletProvider<P extends object>(
  Component: React.ComponentType<P>
) {
  return function WrappedComponent(props: P) {
    return (
      <SolanaWalletProvider>
        <Component {...props} />
      </SolanaWalletProvider>
    );
  };
}

/**
 * Export cluster info for use elsewhere in the app
 */
export const solanaConfig = {
  cluster: SOLANA_CLUSTER,
  rpcEndpoint: RPC_ENDPOINT,
};

export default SolanaWalletProvider;
