/**
 * Polyfills Template
 *
 * Generates polyfills required for Solana Web3.js to work
 * in React Native environment.
 */

import type { TemplateContext } from '../types.js';

export function generatePolyfills(context: TemplateContext): string {
  const { projectName } = context;

  return `/**
 * Crypto Polyfills for React Native
 *
 * Required for @solana/web3.js to work in React Native.
 * Import this file at the very top of your app entry point (index.js or App.js).
 *
 * Generated by SeekerMigrate for ${projectName}
 * @generated
 */

// IMPORTANT: These imports must be at the very top of your entry file,
// before any other imports, especially before @solana/web3.js

// Polyfill for crypto.getRandomValues
import 'react-native-get-random-values';

// Polyfill for Buffer
import { Buffer } from 'buffer';
global.Buffer = Buffer;

// Polyfill for TextEncoder/TextDecoder if needed
if (typeof global.TextEncoder === 'undefined') {
  const { TextEncoder, TextDecoder } = require('text-encoding');
  global.TextEncoder = TextEncoder;
  global.TextDecoder = TextDecoder;
}

// URL polyfill for React Native
if (typeof global.URL === 'undefined') {
  const { URL, URLSearchParams } = require('react-native-url-polyfill');
  global.URL = URL;
  global.URLSearchParams = URLSearchParams;
}

/**
 * Additional setup notes:
 *
 * 1. Install required packages:
 *    npm install react-native-get-random-values buffer text-encoding react-native-url-polyfill
 *
 * 2. For iOS, you may need to run:
 *    cd ios && pod install
 *
 * 3. Import this file at the TOP of your index.js:
 *    import './polyfills';
 *    import { AppRegistry } from 'react-native';
 *    // ... rest of your imports
 */

console.log('[SeekerMigrate] Solana polyfills loaded successfully');
`;
}
