/**
 * Wallet Connect Button Template
 *
 * Generates a React Native component that uses the official
 * @solana-mobile/wallet-adapter-mobile-ui library to render
 * a "Connect Wallet" button and manages the connection state.
 */

import type { TemplateContext } from '../types.js';

export function generateWalletConnectButton(context: TemplateContext): string {
  const { useTypeScript, projectName } = context;
  const ext = useTypeScript ? 'tsx' : 'jsx';

  const typeAnnotations = useTypeScript
    ? `
interface WalletConnectButtonProps {
  onConnect?: (publicKey: string) => void;
  onDisconnect?: () => void;
  style?: object;
}`
    : '';

  const propsType = useTypeScript ? ': WalletConnectButtonProps' : '';

  return `/**
 * WalletConnectButton Component
 *
 * A button component for connecting to Solana wallets using
 * the Mobile Wallet Adapter protocol. Designed for use with
 * Solana Seeker and other Solana Mobile wallets.
 *
 * Generated by SeekerMigrate for ${projectName}
 * @generated
 */

import React, { useCallback, useMemo } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ActivityIndicator,
} from 'react-native';
import { useWallet } from '@solana/wallet-adapter-react';
import {
  transact,
  Web3MobileWallet,
} from '@solana-mobile/mobile-wallet-adapter-protocol-web3js';
import { PublicKey } from '@solana/web3.js';
${typeAnnotations}

export function WalletConnectButton({
  onConnect,
  onDisconnect,
  style,
}${propsType}) {
  const {
    publicKey,
    connected,
    connecting,
    disconnect,
    select,
    wallet,
  } = useWallet();

  const base58PublicKey = useMemo(() => {
    return publicKey?.toBase58() ?? null;
  }, [publicKey]);

  const truncatedAddress = useMemo(() => {
    if (!base58PublicKey) return null;
    return \`\${base58PublicKey.slice(0, 4)}...\${base58PublicKey.slice(-4)}\`;
  }, [base58PublicKey]);

  const handleConnect = useCallback(async () => {
    try {
      // Use Mobile Wallet Adapter to connect
      const authorizationResult = await transact(
        async (wallet${useTypeScript ? ': Web3MobileWallet' : ''}) => {
          // Authorize the app with the wallet
          const authorization = await wallet.authorize({
            chain: 'solana:devnet', // Change to 'solana:mainnet' for production
            identity: {
              name: '${projectName}',
              uri: 'https://your-app-url.com', // Update with your app's URL
              icon: 'favicon.ico', // Update with your app's icon
            },
          });
          return authorization;
        }
      );

      if (authorizationResult?.publicKey) {
        const pubKey = new PublicKey(authorizationResult.publicKey);
        onConnect?.(pubKey.toBase58());
      }
    } catch (error) {
      console.error('Failed to connect wallet:', error);
    }
  }, [onConnect]);

  const handleDisconnect = useCallback(async () => {
    try {
      await disconnect();
      onDisconnect?.();
    } catch (error) {
      console.error('Failed to disconnect wallet:', error);
    }
  }, [disconnect, onDisconnect]);

  if (connecting) {
    return (
      <View style={[styles.button, styles.connectingButton, style]}>
        <ActivityIndicator color="#FFFFFF" size="small" />
        <Text style={styles.buttonText}>Connecting...</Text>
      </View>
    );
  }

  if (connected && base58PublicKey) {
    return (
      <TouchableOpacity
        style={[styles.button, styles.connectedButton, style]}
        onPress={handleDisconnect}
        activeOpacity={0.7}
      >
        <View style={styles.connectedContent}>
          <View style={styles.statusDot} />
          <Text style={styles.buttonText}>{truncatedAddress}</Text>
        </View>
        <Text style={styles.disconnectHint}>Tap to disconnect</Text>
      </TouchableOpacity>
    );
  }

  return (
    <TouchableOpacity
      style={[styles.button, styles.disconnectedButton, style]}
      onPress={handleConnect}
      activeOpacity={0.7}
    >
      <Text style={styles.buttonText}>Connect Wallet</Text>
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  button: {
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 180,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  disconnectedButton: {
    backgroundColor: '#9945FF', // Solana purple
  },
  connectedButton: {
    backgroundColor: '#14F195', // Solana green
  },
  connectingButton: {
    backgroundColor: '#666666',
    flexDirection: 'row',
    gap: 8,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  connectedContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#00FF00',
  },
  disconnectHint: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 12,
    marginTop: 4,
  },
});

export default WalletConnectButton;
`;
}
