/**
 * Report Generator
 *
 * Generates migration reports documenting the changes made,
 * packages to install/remove, and manual steps required.
 */

import * as fs from 'fs';
import * as path from 'path';
import type { MigrationReport, UAM_Auth } from '../schema/uam.js';
import type { ExtendedRule, ParsedAction } from '../rules/index.js';
import type { GeneratedFile } from './types.js';

/**
 * Report generator options
 */
interface ReportOptions {
  outputDir: string;
  projectName: string;
}

/**
 * Report generator class
 */
export class ReportGenerator {
  private options: ReportOptions;

  constructor(options: ReportOptions) {
    this.options = options;
  }

  /**
   * Generate the migration report
   */
  async generate(
    sourceUAM: UAM_Auth,
    rule: ExtendedRule,
    actions: ParsedAction[],
    generatedFiles: GeneratedFile[]
  ): Promise<string> {
    const report = this.buildReport(sourceUAM, rule, actions, generatedFiles);
    const markdown = this.renderMarkdown(report);

    // Write report to file
    const reportPath = path.join(this.options.outputDir, 'MIGRATION_REPORT.md');
    await fs.promises.writeFile(reportPath, markdown, 'utf-8');

    return reportPath;
  }

  /**
   * Build the migration report data structure
   */
  private buildReport(
    sourceUAM: UAM_Auth,
    rule: ExtendedRule,
    actions: ParsedAction[],
    generatedFiles: GeneratedFile[]
  ): MigrationReport {
    const packagesRemoved = actions
      .filter((a): a is Extract<ParsedAction, { type: 'remove_package' }> =>
        a.type === 'remove_package'
      )
      .map((a) => a.packageName);

    const packagesAdded = actions
      .filter((a): a is Extract<ParsedAction, { type: 'add_package' }> =>
        a.type === 'add_package'
      )
      .map((a) => a.packageName);

    return {
      title: `Migration Report: ${rule.name ?? rule.id}`,
      generatedAt: new Date().toISOString(),
      source: {
        method: sourceUAM.method,
        provider: sourceUAM.provider,
        files: sourceUAM.sourceFiles.map((f) => f.path),
      },
      target: {
        method: rule.target.method,
        provider: rule.target.provider,
        ecosystem: rule.target.ecosystem,
      },
      actions: {
        packagesRemoved,
        packagesAdded,
        filesGenerated: generatedFiles.map((f) => f.path),
        filesModified: [],
      },
      manualSteps: rule.migrationSteps ?? [],
      notes: rule.behavioralNotes ?? [],
    };
  }

  /**
   * Render the report as Markdown
   */
  private renderMarkdown(report: MigrationReport): string {
    const lines: string[] = [];

    // Header
    lines.push(`# ${report.title}`);
    lines.push('');
    lines.push(`> Generated by SeekerMigrate on ${new Date(report.generatedAt).toLocaleString()}`);
    lines.push('');

    // Summary
    lines.push('## Summary');
    lines.push('');
    lines.push('This report documents the migration from Firebase Email Authentication to Solana Seeker wallet authentication.');
    lines.push('');
    lines.push(`| Aspect | Source | Target |`);
    lines.push(`|--------|--------|--------|`);
    lines.push(`| Method | ${report.source.method} | ${report.target.method} |`);
    lines.push(`| Provider | ${report.source.provider} | ${report.target.provider} |`);
    lines.push(`| Ecosystem | Firebase | ${report.target.ecosystem} |`);
    lines.push('');

    // Source files detected
    lines.push('## Source Files Detected');
    lines.push('');
    lines.push('The following files contained Firebase authentication code:');
    lines.push('');
    for (const file of report.source.files) {
      lines.push(`- \`${file}\``);
    }
    lines.push('');

    // Package changes
    lines.push('## Package Changes');
    lines.push('');

    if (report.actions.packagesRemoved.length > 0) {
      lines.push('### Packages to Remove');
      lines.push('');
      lines.push('```bash');
      lines.push(`npm uninstall ${report.actions.packagesRemoved.join(' ')}`);
      lines.push('```');
      lines.push('');
    }

    if (report.actions.packagesAdded.length > 0) {
      lines.push('### Packages to Install');
      lines.push('');
      lines.push('```bash');
      lines.push(`npm install ${report.actions.packagesAdded.join(' ')}`);
      lines.push('```');
      lines.push('');
    }

    // Generated files
    lines.push('## Generated Files');
    lines.push('');
    lines.push('The following files have been generated in the `seekermigrate-output/` directory:');
    lines.push('');
    for (const file of report.actions.filesGenerated) {
      lines.push(`- \`${file}\``);
    }
    lines.push('');

    // Migration steps
    lines.push('## Migration Steps');
    lines.push('');
    lines.push('Follow these steps to complete the migration:');
    lines.push('');
    report.manualSteps.forEach((step, index) => {
      lines.push(`${index + 1}. ${step}`);
    });
    lines.push('');

    // Integration guide
    lines.push('## Integration Guide');
    lines.push('');
    lines.push('### 1. Add Polyfills');
    lines.push('');
    lines.push('Add the polyfills import at the very top of your `index.js`:');
    lines.push('');
    lines.push('```javascript');
    lines.push("import './seekermigrate-output/polyfills';");
    lines.push("import { AppRegistry } from 'react-native';");
    lines.push("// ... rest of your imports");
    lines.push('```');
    lines.push('');

    lines.push('### 2. Wrap Your App');
    lines.push('');
    lines.push('Wrap your app with the SolanaWalletProvider:');
    lines.push('');
    lines.push('```jsx');
    lines.push("import { SolanaWalletProvider } from './seekermigrate-output/SolanaWalletProvider';");
    lines.push('');
    lines.push('function App() {');
    lines.push('  return (');
    lines.push('    <SolanaWalletProvider>');
    lines.push('      <YourExistingApp />');
    lines.push('    </SolanaWalletProvider>');
    lines.push('  );');
    lines.push('}');
    lines.push('```');
    lines.push('');

    lines.push('### 3. Replace Login Component');
    lines.push('');
    lines.push('Replace your existing login form with the WalletConnectButton:');
    lines.push('');
    lines.push('```jsx');
    lines.push("import { WalletConnectButton } from './seekermigrate-output/WalletConnectButton';");
    lines.push("import { useAuth } from './seekermigrate-output/WalletAuthContext';");
    lines.push('');
    lines.push('function LoginScreen() {');
    lines.push('  const { isAuthenticated, user } = useAuth();');
    lines.push('');
    lines.push('  if (isAuthenticated) {');
    lines.push('    return <Text>Welcome, {user.publicKey}</Text>;');
    lines.push('  }');
    lines.push('');
    lines.push('  return (');
    lines.push('    <View>');
    lines.push('      <Text>Connect your Solana wallet to continue</Text>');
    lines.push('      <WalletConnectButton />');
    lines.push('    </View>');
    lines.push('  );');
    lines.push('}');
    lines.push('```');
    lines.push('');

    // Behavioral notes
    if (report.notes.length > 0) {
      lines.push('## Important Behavioral Differences');
      lines.push('');
      lines.push('> **Note:** The migration changes how authentication works. Please review these differences:');
      lines.push('');
      for (const note of report.notes) {
        lines.push(`- ${note}`);
      }
      lines.push('');
    }

    // Cleanup
    lines.push('## Cleanup');
    lines.push('');
    lines.push('After verifying the migration works correctly:');
    lines.push('');
    lines.push('1. Remove old Firebase authentication files');
    lines.push('2. Remove Firebase configuration from your app');
    lines.push('3. Update any backend services to accept wallet signatures instead of Firebase tokens');
    lines.push('4. Update your privacy policy to reflect the new authentication method');
    lines.push('');

    // Testing
    lines.push('## Testing');
    lines.push('');
    lines.push('Before deploying to production:');
    lines.push('');
    lines.push('1. **Test with Solana Mobile Stack Simulator** - Use the Android emulator with fake wallet');
    lines.push('2. **Test on physical device** - Install a Solana wallet app (Phantom, Solflare, etc.)');
    lines.push('3. **Test with Seeker** - If you have access to a Seeker device, test the native experience');
    lines.push('4. **Verify dApp Store compliance** - Review Solana dApp Store guidelines');
    lines.push('');

    // Resources
    lines.push('## Resources');
    lines.push('');
    lines.push('- [Solana Mobile Documentation](https://docs.solanamobile.com/)');
    lines.push('- [Mobile Wallet Adapter](https://github.com/solana-mobile/mobile-wallet-adapter)');
    lines.push('- [Solana dApp Store](https://dappstore.solanamobile.com/)');
    lines.push('- [Seeker Documentation](https://docs.solanamobile.com/seeker)');
    lines.push('');

    lines.push('---');
    lines.push('');
    lines.push('*This report was generated by [SeekerMigrate](https://github.com/seekermigrate)*');

    return lines.join('\n');
  }
}
